Undertow 1816
undertow-io/undertow pull request #1000
Opened 2020-12-01 09:25 UTC by spyrkob

Issue: https://issues.redhat.com/browse/UNDERTOW-1816

2020-12-02 18:09 UTC, fl4via requested changes

2020-12-02 18:09 UTC, fl4via commented on servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java
> + * Copyright 2014 Red Hat, Inc., and individual contributors
it should be 2020

2020-12-02 18:09 UTC, fl4via commented on servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueSslServletTestCase.java
> + * Copyright 2014 Red Hat, Inc., and individual contributors
same here

2020-12-02 18:48 UTC, fl4via approved these changes

2020-12-02 19:34 UTC, fl4via commented
@spyrkob  it appears that the fix is causing the tests to loop

2020-12-03 00:45 UTC, fl4via commented
@spyrkob I ran this in my system. The HttpContinueConduitWrappingHandlerBufferLeakTestCase is looping or freezing.

2020-12-03 03:28 UTC, fl4via commented
This is the test that is freezing. It is trying to read a response and is not getting any answer: HttpContinueConduitWrappingHandlerBufferLeakTestCase.testEmptySSLHttpContinueNoLeak:

`"main" #1 prio=5 os_prio=0 tid=0x00007effc400a800 nid=0x3b7f runnable [0x00007effc8aeb000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
        - locked <0x00000000fbd4ca50> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000000fbd4cb30> (a sun.security.ssl.AppInputStream)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:71)
        - locked <0x00000000fbd4cb30> (a sun.security.ssl.AppInputStream)
        at io.undertow.server.handlers.HttpContinueConduitWrappingHandlerBufferLeakTestCase.testEmptySSLHttpContinueNoLeak(HttpContinueConduitWrappingHandlerBufferLeakTestCase.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

2020-12-03 10:17 UTC, spyrkob commented
@fl4via the hanging test can be fixed by changing the request to HTTP/2.0 rather than HTTP/1.1 so that upgrade doesn't happen. But there's also another issue - it seems with http2 enabled terminating request in HttpContinueReadHandler is not enough and HttpContinueConduitWrappingHandlerBufferLeakTestCase#testHttpContinueRejectedBodySentAnywayNoBufferLeak still fails.

2020-12-03 13:48 UTC, fl4via commented
@spyrkob  I'll be afk in the next couple of hours, so feel free to investigate this one if you want. I'll look into this early in the afternoon, after a team call I have scheduled for noon. If you find anything, ping me or post it here so I can pick up from where you left :-) Thanks!

2020-12-04 13:12 UTC, spyrkob commented
I can't reproduce this fails in my env. I don't know if it's worth trying to run the CU again?

2020-12-06 21:55 UTC, merged