[UNDERTOW-1198] - fix IPv6 matching regex to include compressed repre…
undertow-io/undertow pull request #1160
Opened 2021-05-31 07:06 UTC by baranowb

…sentation. Fix ACL
Issue: https://issues.redhat.com/browse/UNDERTOW-1198

2021-06-01 08:34 UTC, ropalka commented on core/src/main/java/io/undertow/util/NetworkUtils.java
> +     */
[Non capturing groups](https://www.regular-expressions.info/brackets.html):
The above expression should be:

either (one non capturing group)

^(
(?:([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4})
|(?:([0-9a-fA-F]{1,4}:){1,7}:)
|(?:([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4})
|(?:([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2})
|(?:([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3})
|(?:([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4})
|(?:([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5})
|(?:[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6}))
|(?::((:[0-9a-fA-F]{1,4}){1,7}|:))
)$

or (multiple non capturing groups)

(
(?:[0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}
|(?:[0-9a-fA-F]{1,4}:){1,7}:
|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}
|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}
|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}
|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}
|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}
|[0-9a-fA-F]{1,4}:(?:(:[0-9a-fA-F]{1,4}){1,6})
|:(?:?((:[0-9a-fA-F]{1,4}){1,7}|:))
)

in order to be consistent.

2021-06-01 11:44 UTC, ropalka approved these changes
LGTM

2021-09-16 11:40 UTC, msfm requested changes

2021-09-16 11:44 UTC, msfm commented on core/src/main/java/io/undertow/UndertowMessages.java
>  }
I think the same conflict issue can happen with [PR for 2.0.x branch](https://github.com/undertow-io/undertow/pull/1162/files#diff-a503bdb32421a0a08548181d1aad3671f05712fadac9ddb0f732013e4163a0ef) as the same change for [UNDERTOW-1858](https://issues.redhat.com/browse/UNDERTOW-1858) has also been merged in 2.0.x branch.

2021-09-27 12:04 UTC, merged