[UNDERTOW-2138] Removing unnecessary JDK8 reflection hacks - API is available on supported JDKs
undertow-io/undertow pull request #1355
Opened 2022-08-01 08:56 UTC by ropalka

https://issues.redhat.com/browse/UNDERTOW-2138

2022-08-11 02:32 UTC, fl4via approved these changes

2022-08-11 02:38 UTC, fl4via requested changes
I don't think the JDK9 classes are needed either.
The question here, though, is, do we require JDK11 to build or do we require JDK11 to run as well?

2022-08-16 22:42 UTC, ropalka commented
The JDK9AlpnProvider class is still necessary on JDK11 and above. Just the class name is unlucky and confusing @fl4via .
I updated this PR with renaming this class from JDK9AlpnProvider to ModularJdkAlpnProvider to better describe it's purpose.

2022-09-09 14:42 UTC, fl4via approved these changes

2022-09-09 15:18 UTC, merged