[UNDERTOW-2147] fix race condition between session changeSessionId and invalidate"
undertow-io/undertow pull request #1370
Opened 2022-08-30 21:43 UTC by aogburn

https://issues.redhat.com/browse/UNDERTOW-2147

2022-09-06 05:35 UTC, fl4via requested changes

2022-09-06 05:35 UTC, fl4via commented on core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
> +                if (invalid || invalidationStarted) {
just invalidationStarted is enough here

2022-09-06 21:40 UTC, aogburn commented on core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
> +                if (invalid || invalidationStarted) {
Done

2022-09-17 11:53 UTC, fl4via approved these changes

2022-09-17 15:17 UTC, fl4via approved these changes

2022-09-17 19:33 UTC, merged