UNDERTOW-2228 Undertow write-timeout can cause a truncate response for request coming through keep-alive connection
undertow-io/undertow pull request #1475
Opened 2023-05-11 11:21 UTC by TomasHofman

https://issues.redhat.com/browse/JBEAP-24358 
https://issues.redhat.com/browse/UNDERTOW-2228

This change resets the expireTime variable in the
WriteTimeoutStreamSinkConduit at the end of each request. This should
prevent a subsequent request on the same connection to be affected by
timeout counter started during a previous request.

2023-05-11 11:22 UTC, TomasHofman commented
FYI @fl4via

2023-06-06 06:52 UTC, fl4via requested changes
We will need to keep the old constructor as this is public API

2023-06-06 07:44 UTC, TomasHofman commented
Thanks! I added the original constructor back.

2023-06-07 04:21 UTC, fl4via approved these changes

2023-06-08 15:03 UTC, TomasHofman commented
I can reproduce the Windows test freeze on a Windows VM easily, but so far didn't manage to do anything about it.

Attaching stacktrace screenshot of where the test case gets stuck (didn't manage to get clipboard sharing working with the Windows VM :) ). At first sight it looks like the httpclient gets stuck when reading the response entity, but it could be caused by some discrepancy on undertow side I guess...

![Screenshot from 2023-06-08 15-11-35](https://github.com/undertow-io/undertow/assets/353221/19e55c2c-1dcb-43ed-94b6-e6d0aea479a1)

2023-06-09 18:25 UTC, TomasHofman commented
Hello @fl4via , the stuck Windows tests are gone. There is one failure in DefaultServletCachingListenerTestCase in the "Undertow CI / JDK 17 - servlet - ubuntu-latest" which looks unrelated to me. Locally is passing.

2023-06-13 15:40 UTC, fl4via commented
Thanks @TomasHofman !
The failure is unrelated indeed. I was able to reproduce that issue in my computer once and verify why is the file failing to refresh. This issue arises when the OS has too many open files at the same time and it can't update it. You need to change a configuration in the Linux where you say how many open files are supported. When you increase the number in that config, the failure is sorted out. And it happens intermittently because it depends on the state of the OS at the moment it runs CI.

2023-06-14 02:49 UTC, merged