[UNDERTOW-2287] Add ACL style ip-match predicate
undertow-io/undertow pull request #1502
Opened 2023-07-10 07:33 UTC by baranowb

2023-07-12 06:17 UTC, fl4via approved these changes

2023-07-28 16:48 UTC, ropalka requested changes
Please add back the static class modifier otherwise every subclass of IPMatchBase will have its own inner classes created and it will cost much more memory.

2023-07-28 16:48 UTC, ropalka commented on core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
> +    protected abstract class PeerMatch {
static modifier got lost during the refactoring

2023-07-28 16:48 UTC, ropalka commented on core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
> +    protected class ExactIpV4PeerMatch extends PeerMatch {
Same here, static modifier got lost during the refactoring

2023-07-28 16:48 UTC, ropalka commented on core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
> +    protected class ExactIpV6PeerMatch extends PeerMatch {
Same here, static modifier got lost during the refactoring

2023-07-28 16:48 UTC, ropalka commented on core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
> +    protected class PrefixIpV4PeerMatch extends PeerMatch {
Same here, static modifier got lost during the refactoring

2023-07-28 16:48 UTC, ropalka commented on core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java
> +    protected class PrefixIpV6PeerMatch extends PeerMatch {
Same here, static modifier got lost during the refactoring

2023-08-03 22:44 UTC, ropalka approved these changes

2024-07-29 10:03 UTC, merged