initialize the DefaultServer once to speed up test HttpContinueSslServletTestCase
undertow-io/undertow pull request #1574
Opened 2024-04-03 03:39 UTC by TestBoost

There are five tests in the test class `HttpContinueSslServletTestCase`. However, they reply on the same DefaultServer to send post http request. The time cost of start or stop for the DefaultServer is high. They are not modifying the contents of the DefaultServer, thus we can just initialize the DefaultServer once before or after all test methods inside test class `HttpContinueSslServletTestCase`.

The test runtime can jump from `5.43160 s` to `1.8027 s` after applying these changes when run on our machine.

2024-04-03 07:23 UTC, baranowb commented
@TestBoost Could you please create a ticket?

2024-04-03 20:53 UTC, TestBoost commented
Sure, I just submit a ticket here https://issues.redhat.com/browse/UNDERTOW-2371. I don't know why the test class `Http2ClientTestCase` fails because the DefaultServer is already closed. Maybe we also need some checks in the test `Http2ClientTestCase` too.

2024-06-24 10:47 UTC, baranowb commented
@TestBoost could you please force push again to trigger CI?

2024-08-07 10:15 UTC, ropalka approved these changes

2024-10-09 09:11 UTC, baranowb requested changes
If marked method is not used, it should be removed?

2024-10-09 09:11 UTC, baranowb commented on servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java
> +    public static void before() throws Exception {
Is this method even used now?

2024-11-26 07:50 UTC, merged