[UNDERTOW-2273] Change ExchangeAttributeParser so it correctly handle…
undertow-io/undertow pull request #1575
Opened 2024-04-05 10:25 UTC by xjusko

…s nested attributes.
https://issues.redhat.com/browse/UNDERTOW-2273

2024-06-24 10:45 UTC, baranowb requested changes
Needs a simple test case?

2024-06-26 15:43 UTC, ropalka requested changes
LGTM - please provide a simple test case.

2024-07-08 07:21 UTC, xjusko commented
@baranowb @ropalka I added a simple test for parsing. I will edit/add tests with nested attributes once I implement some in future PR.

2024-07-11 08:22 UTC, baranowb approved these changes

2024-08-07 10:16 UTC, ropalka approved these changes

2024-09-04 08:55 UTC, merged