[UNDERTOW-2422] Return the protocol field of the HttpServerExchange into the status line
undertow-io/undertow pull request #1644
Opened 2024-08-06 00:47 UTC by EarthJeff

Currently, no matter what you set the HttpServerExchange.protocol field to, the value "HTTP/1.1" will always be used. This change will use the value of the protocol field (or "HTTP/1.1" if the field is empty) in the HTTP response's status line.

There is a test included in this PR. It confirms the default behavior and the new behavior.

2024-08-06 17:32 UTC, ropalka approved these changes

2024-08-13 01:01 UTC, EarthJeff commented
@ropalka The two test failures on JDK17-core, Mac and Windows, are "Buffer Leaks", which are listed as intermittent in the known test issues ticket. The failure in testRstOnPush in JDK11-ipv6 on ubuntu is, I think, another intermittent. I believe in the prior CI run, this same test failed in a different environment, and succeeded in this run. I believe that this CI run should be treated as having succeeded and that testRstOnPush should be added to the known issues list.

2024-08-14 08:37 UTC, baranowb approved these changes
Id merge those 4 into 1 commit.

2024-08-19 17:32 UTC, EarthJeff commented
I have squashed the 4 commits into 1.

2024-08-22 16:01 UTC, fl4via requested changes

2024-08-22 16:01 UTC, fl4via commented on core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java
> + * JBoss, Home of Professional Open Source.
Please, update the year to 2024

2024-08-22 16:01 UTC, fl4via commented on core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
> +                // append status code, reasopn phrase, and headers
small typo

2024-08-22 20:25 UTC, EarthJeff commented
@fl4via I have made the requested changes (and squashed the commit).

2024-09-18 14:08 UTC, fl4via approved these changes

2024-10-04 09:59 UTC, merged