[UNDERTOW-2444] Fix RST scenario violation in H2
undertow-io/undertow pull request #1663
Opened 2024-09-19 08:32 UTC by baranowb

Issue: https://issues.redhat.com/browse/UNDERTOW-2444
2.4.x: https://github.com/undertow-io/undertow/pull/1662
2.3.x:
2.2.x:

2024-09-29 05:31 UTC, rhusar requested changes

2024-09-29 05:31 UTC, rhusar commented on core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
> +         * flag indicate whether our side originated. This is done for caching purposes, handlng differs.
s/handlng/handling

2024-09-29 05:31 UTC, rhusar commented on core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
> +         * @return
This Javadoc needs to be improved, it's really not clear what is meant here.

2024-10-04 07:38 UTC, fl4via commented
@baranowb I'm closing this PR so we can backport in bulk, to avoid overusing CI resources and to follow the procedure we have for the Undertow backport of PRs

2024-10-04 07:38 UTC, closed without merging