UNDERTOW-1622: Implement blocking IO timeouts
undertow-io/undertow pull request #837
Opened 2020-01-03 18:54 UTC by carterkozak

Implemented a new BlockingTimeoutHandler which can be configured
with I/O timeouts for blocking read and write operations.

This approach limits the time that may be spent in awaitReadable
or awaitWritable to apply to only blocking operations without requiring
invasive code change.

2020-01-03 18:56 UTC, carterkozak commented on core/src/main/java/io/undertow/server/handlers/BlockingTimeoutHandler.java
> +public final class BlockingTimeoutHandler implements HttpHandler {
Open question: should this be split into separate BlockingReadTimeoutHandler and BlockingWriteTimeoutHandler?

2020-01-05 21:57 UTC, carterkozak commented
Failing jdk11 tests appear to be unrelated to this change, but may be related to:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8198562
similar netty issue:
https://github.com/netty/netty/issues/8697#issuecomment-450619821

2020-01-08 14:35 UTC, carterkozak commented on core/src/main/java/io/undertow/server/handlers/BlockingTimeoutHandler.java
> +public final class BlockingTimeoutHandler implements HttpHandler {
I think this makes more sense to split into separate handlers for read and write timeouts, that way each one is responsible for exactly one thing.

2020-01-08 14:37 UTC, carterkozak commented on core/src/main/java/io/undertow/server/handlers/BlockingTimeoutHandler.java
> +                IoUtils.safeClose(serverConnection);
Might be helpful to log something at debug level here and in the write timeout conduit when the timeout is reached.

2020-09-11 05:11 UTC, fl4via requested changes

2020-09-11 05:11 UTC, fl4via commented on core/src/test/java/io/undertow/server/handlers/BlockingWriteTimeoutHandlerTestCase.java
> + * Copyright 2014 Red Hat, Inc., and individual contributors
I'll update these headers before merging.

2020-09-11 06:07 UTC, fl4via approved these changes

2020-09-11 06:40 UTC, merged